### ISSUE TITLE
VSCode Output panel toggles open on load

### ISSUE THREAD

**Issue by AndyCormack** [SoulcodeAgency/vscode-unwanted-extensions#10]
### Problem

After a recent update to the extension or VSCode (unsure which is the root cause) whenever I open a project that has unwanted extensions configured it triggers opening the Output panel for the extension.

As you can imagine, opening many repos or reloading the window over the course of a work day adds up to a lot of times this happens in a given day and becomes quite annoying!

### Sidenote

I'd also like to say I appreciate that you've take over maintaining this extension! It's quite helpful at work to make sure my team don't have the wrong things running and I'd hate for it to disappear.

**Comment by Cyclodex** [comment]
Hi @AndyCormack , thanks for the feedback. I have the same feelings. I will have a look at it soon, what could be the issue with logging.

**Comment by Cyclodex** [comment]
@AndyCormack just published a new version 1.2.3 which should fix the issue. Thanks for the issue and all the best!

**Comment by AndyCormack** [comment]
Thanks! Very much appreciated.
