### ISSUE TITLE
I don't know if this is vscode issue or on your side, but vscode migration text says migrate to inline sql

### ISSUE THREAD

**Issue by allusernamestakenexceptthis** [SoulcodeAgency/vscode-unwanted-extensions#4]
the message was a bit confusing. not sure if this is caused by vscode or on your side.   I got popup about depreciated extensions. clicked on it, it showed me the old extension and it says migrate to inline sql.  I was thinking how is that related. but click on inline sql and saw the new extension.

**Comment by Cyclodex** [comment]
Thanks for reporting, yes this was known and very unfortunate. Sorry.
But it was a bug from VSCode / Microsoft team, entering the wrong extension name there.
They have solved it finally!

I had to deprecate the old version, there is now a [new extensions](https://marketplace.visualstudio.com/items?itemName=Soulcode.vscode-unwanted-extensions) which is maintained and gets updated.
I just did not had any access anymore to the old publisher.
