### ISSUE TITLE
"recommondations" in extensionsVersionCheck.json have no effect

### ISSUE THREAD

**Issue by RedX2501** [SoulcodeAgency/vscode-unwanted-extensions#7]
This happens with version 1.1.2.

Is it a documentation error and the key "recommendations" is ignored in that file or am I doing something wrong?

I tried:

File: "extensionsVersionCheck.json"
```
{
    "recommendations":[
        "stkb.rewrap@>=17.8"
    ],
   "unwantedRecommendations": []
}
```

But received no message box.

Here is the output of the extension:

```
###  Checking... ###

Found extension configuration in c:\data\Silt5\.vscode\extensionsVersionCheck.json
Found extension configuration in c:\data\Silt5\.vscode\extensions.json
No unwanted extensions found.
```

So what's the point of having the `recommendations` in "extensionVersionCheck.json"?

**Comment by Cyclodex** [comment]
Hey, this project is about unwanted recommendations, therefor nothing yet about recommendations.

Its written in the documentation, but yes i can also delete this empty prop there, to be more clear. Thanks for the issue

Ps: so you must declare the unwanted versions, not the wanted.

**Comment by Cyclodex** [comment]
Could you solve your problem with the version definition within the `"unwantedRecommendations"`?

I already made an update on dev, to make sure its clear that `"recommendations"` are not supported (yet):
https://github.com/SoulcodeAgency/vscode-unwanted-extensions/commit/a5298d088fb3f77f51d311c42716de20e1eac04c

**Comment by RedX2501** [comment]
Yeah it works with the unwanted recommendation.

**Comment by Cyclodex** [comment]
@RedX2501 Great and thanks for closing - please feel free to give a rating & review on https://marketplace.visualstudio.com/items?itemName=Soulcode.vscode-unwanted-extensions&ssr=false#review-details
Would be appreciated!
