### ISSUE TITLE
Doesn't work?

### ISSUE THREAD

**Issue by NullVoxPopuli** [SoulcodeAgency/vscode-unwanted-extensions#9]
I have recommendations working, but not this extension's described behavior.

The most activity I could find in the Output logs for Extension Host is:
```
2024-10-23 14:49:49.656 [info] ExtensionService#_doActivateExtension Soulcode.vscode-unwanted-extensions, startup: true, activationEvent: 'workspaceContains:.vscode/extensions.json'

```

and _that's it_.

no errors as far as I can tell, and this extension doesn't have an output channel of its own. 

I haven't debugged anything, but is there is a configuration that is needed? All I did was install the extension, and my extensions.json has comments (without the jsonc extension, because that's what VSCode does... break json conventions 😅 )

**Comment by NullVoxPopuli** [comment]
even if I remove the comments, I don't see any warning behavior with my installed unwantedRecommendations

**Comment by NullVoxPopuli** [comment]
I saw the screenshot in the README looked like windows -- maybe this extension doesn't work on *nix machineS?

**Comment by NullVoxPopuli** [comment]
I can "run" check for unwanted extensions:
![image](https://github.com/user-attachments/assets/5e51cb05-16db-4fb4-b25f-01a44f5302e1)

but it also appears to do nothing

**Comment by NullVoxPopuli** [comment]
I found that if I switch to the pre-release version, there is an output channel, and I see the logs specified in code. 

![image](https://github.com/user-attachments/assets/bc4a7f6c-42f1-4c44-8f56-6418df92edf2)


does this extension need to be promoted to stable release?

**Comment by NullVoxPopuli** [comment]
seems it still doesn't report anything unwanted.

can more output be added to the output channel? 
like:
- what does it see?
- does it know I have an unwantedRecommendations list?

**Comment by Cyclodex** [comment]
> I saw the screenshot in the README looked like windows -- maybe this extension doesn't work on *nix machineS?

Unsure if this is the problem currently and if *nix is supported. Lets verify that.

@NullVoxPopuli Could you maybe provide your `.vscode/extensions.json`? Thanks

I will try to look into this in the next days and extend the output channel information if possible.

**Comment by NullVoxPopuli** [comment]
yea, 

<details><summary>here you go</summary>

```
{
  "recommendations": [
    "bierner.markdown-preview-github-styles", // Markdown Preview Github Styling
    "eamodio.gitlens", // GitLens
    "visualstudioexptteam.vscodeintellicode", // IntelliCode
    "typed-ember.glint-vscode", // Glint (Ember Template Types)

    // Includes
    // - syntax highlighting
    // - language server
    // - eslint
    // - stylelint
    // - prettier
    // - editorconfig
    //
    // https://marketplace.visualstudio.com/items?itemName=EmberTooling.emberjs
    "embertooling.emberjs",
    // But if someone removes one, just recommending the extension pack isn't enough to
    // recommend the individual extensions again
    "embertooling.vscode-ember",
    "lifeart.vscode-glimmer-syntax",
    "dbaeumer.vscode-eslint",
    "EditorConfig.EditorConfig",
    "esbenp.prettier-vscode",
    "stylelint.vscode-stylelint",

    // Warns if any of the below are present
    "Soulcode.vscode-unwanted-extensions"
  ],
  "unwantedRecommendations": [
    // None of these are particularly useful for Ember development
    "googlecloudtools.cloudcode", // Google Cloud Code
    "ms-kubernetes-tools.vscode-kubernetes-tools", // Kubernetes

    // out of date gjs and gts syntax highlighting.
    "chiragpat.vscode-glimmer",
    // old version of the language server built in to embertooling
    "lifeart.vscode-ember-unstable",
    // out of date fork for linkedin
    "suchitadoshi1987.vscode-ember-experimental",
    // out of date
    "dhedgecock.ember-syntax",
    // theme, unrelated to ember
    "jgibson.ember-color-theme",
    // don't use jest
    "Orta.vscode-jest"
  ]
}
```


</details>

**Comment by Cyclodex** [comment]
@NullVoxPopuli okey, I extended the logging, I hope this will help us further identifying maybe the issue.

Also I checked on MacOS, where it also works for me. I don't have an other *nix like system running.
Which system are you running?

Can you make sure you run the extension on its latest version, which was just published: *1.2.1*
https://marketplace.visualstudio.com/items?itemName=Soulcode.vscode-unwanted-extensions

It should then, show according logging details:

![image](https://github.com/user-attachments/assets/9645bea0-eb15-4734-849f-d536689c391f)

**Comment by NullVoxPopuli** [comment]
it looks like it _does_ work, but is just _very slow_, and because I don't _main_ vs code, I don't have it open long enough for the dialog to display
![image](https://github.com/user-attachments/assets/958428bd-51aa-4ad8-bdc4-03363a6b2224)

**Comment by NullVoxPopuli** [comment]
ah here is why:
```
Found configuration in file: <.pnpm>/node_modules/<project-a>/node_modules/<project-b>/node_modules/<project-c>/node_modules/<dependency-a>/.vscode/extensions.json
Found configuration in file: <repo>/libraries/<project-d>/node_modules/<dependency-a>/.vscode/extensions.json
Found configuration in file: <.pnpm>/node_modules/<project-a>/node_modules/<project-b>/node_modules/<project-e>/node_modules/<project-c>/node_modules/<dependency-a>/.vscode/extensions.json

Found 7133 recommended extensions defined in the configuration
Found 10 unwanted extensions defined in the configuration
```

So it seems like this plugin needs to exclude `node_modules`

**Comment by Cyclodex** [comment]
@NullVoxPopuli There is already an exclude pattern, to ignore `node_modules`, but it somehow had a invisible character which broke it.

A new release (1.2.2) is getting deployed now. I hope this will solve your issues finally! Let me know!

**Comment by NullVoxPopuli** [comment]
it does! thank you!!

**Comment by Cyclodex** [comment]
@NullVoxPopuli Thank you for your inputs and being patient.

Closing the issue, have fun! 🙏
